### ISSUE TITLE
Request components example

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#104]
Add an example that shows how to use all the various components associated with the initial `Request` that Gotham providers via `State`.

**Comment by n-pochet** [comment]
@bradleybeddoes When you say that you want to show 

> how to use all the various components associated with the initial `Request`

could a kind of echo server be a good example for you?

**Comment by bradleybeddoes** [comment]
That is essentially what I had in mind as well, possibly the lazy approach in just using `println!`.

This weekend I am going to make some further refinements to the examples directory to group examples by functionality being demonstrated e.g. a `routing` directory under which examples related to routing will exist going forward.

To that end it might be a good idea to hold off on any new PR until I make those changes so I don't cause you any hassle.

**Comment by n-pochet** [comment]
No problem. I will prepare them and wait for your changes.

**Comment by bradleybeddoes** [comment]
Closed by #141.
