### ISSUE TITLE
Create multi pipeline example

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#111]

**Comment by colinbankier** [comment]
I'm happy to take a stab at this - but I'm not sure exactly what was initially intended.
There are some examples of multi pipelines from https://github.com/gotham-rs/gotham/pull/191 and https://github.com/gotham-rs/gotham/issues/190 and https://github.com/gotham-rs/gotham/issues/258

I imagine just something similar, but in a stand-alone example.
I'm thinking an example showing different pipelines for serving html and a json api could be a common use-case. @bradleybeddoes - anything else specific you intended to demonstrate here?

**Comment by msrd0** [comment]
I believe this was done in #287
