### ISSUE TITLE
Create Post example (multipart/form-data)

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#114]

**Comment by rajcspsg** [comment]
Hi @bradleybeddoes - Can I work on this issue for adding documentation?

**Comment by bradleybeddoes** [comment]
Hey there @rajcspsg - You're certainly very welcome to get involved but we're still trying to figure out the multipart implementation. You might like to contribute to the discussion around this in #11 in the interim.

**Comment by rajcspsg** [comment]
Thanks @bradleybeddoes . I'm very new to rust programming and still learning. So I would like to pick some documentation work.

**Comment by paulzhang5511** [comment]
add multipart example https://github.com/paulzhang5511/gotham/blob/master/examples/handlers/multipart/src/main.rs

**Comment by paulzhang5511** [comment]
@bradleybeddoes I #347 merged.
