### ISSUE TITLE
Create async handler example

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#115]

**Comment by thedodd** [comment]
A super easy way to do it (based on some GraphQL work I've been doing):
```rust
// ... snip ...

    /// The handler for executing GraphQL requests.
    pub fn graph(state: State) -> Box<HandlerFuture> {
        Box::new(GatewayService::_graph(state))
    }

    /// Business logic implementation of handling GraphQL requests.
    #[async]
    fn _graph(mut state: State) -> Result<(State, Response), (State, HandlerError)> {
        // Begin tracing this graph request.
        let uri = String::from(Uri::borrow_from(&state).path());
        let _span = (*APISpan::borrow_from(&state)).child(uri, |ctx| ctx.start());

        // Extract the request body.
        let body_res = await!(Body::take_from(&mut state).concat2().map(|chunks| chunks.to_vec()));
        // ... snip ...
    }

// ... snip ...
```

Works like a charm; though I would love to be able to not have the top-level indirect for boxing the future (having just one fn, instead of `graph` & `_graph`).

**Comment by alsuren** [comment]
I'm currently in the process of writing some examples that use hyper::Client and `.and_then()` and `.join()`.

@thedodd does `#[async]` still require nightly? I will probably mention it, but I'm trying to stick to things that are available in stable rust.

**Comment by bradleybeddoes** [comment]
Great async handler examples created by @alsuren available at https://github.com/gotham-rs/gotham/tree/master/examples/handlers
