### ISSUE TITLE
Release a version

### ISSUE THREAD

**Issue by rap2hpoutre** [gotham-rs/gotham#154]
Since there were no release since sept 2017 and master is 300+ commits ahead, did you plan any relase? 

It's `0.something` so I think it's OK to release even if it has breaking changes and unfinished things. I'm asking this because, I wanted to recreate something from the examples given on the repository, and it did not work because of some breaking changes (think about `gotham::start`). I don't want to start my project in 0.1.2, because to many things seems to have changed, so I use the master branch.

_Side note: I will check the "help wanted" tagged issues and try to help you, it will be more productive! Still I'm not a good rust developer, just a tinkerer, so I'm not sure my help will be valuable_

Thanks for your work on this (great) web framework!

**Comment by bradleybeddoes** [comment]
Hi @rap2hpoutre, welcome to the Gotham community.

Yes there is a [release planned](https://github.com/gotham-rs/gotham/milestone/2) and we've been telling folks Q1 2018, that is still accurate. 

I suspect it may even end up being this month, given recent progress.

You can be amongst the first to know when it ships via https://gitter.im/gotham-rs/gotham or https://twitter.com/gotham_rs.

**Comment by rap2hpoutre** [comment]
thank you!
