### ISSUE TITLE
Add an Integration / Quick Start section to README

### ISSUE THREAD

**Issue by jeffbarg** [gotham-rs/gotham#169]
Thanks very much for this project!

It would be helpful to add an integration section to the README (i.e. instead of just having the examples folder, add a section on how to use Gotham in an existing / new independent project)

**Comment by bradleybeddoes** [comment]
Hi @jeffbarg, welcome to the Gotham community.

Could you provide us with some examples of the kind of content you’d like to see? Perhaps links to content from other OSS projects?

Alternatively I’d be very happy to consider a PR implementing this.

**Comment by bradleybeddoes** [comment]
Closing until further updates are available.
