### ISSUE TITLE
A panic inside a handler should return HTTP 500, not kill the server

### ISSUE THREAD

**Issue by coder543** [gotham-rs/gotham#17]
Running the example app, it's easy to cause a panic with this message:

    thread '<unnamed>' panicked at 'attempt to add with overflow', src/controllers/challenge.rs:34

simply by visiting this address: http://127.0.0.1:7878/challenge/Rustacean?count=255

If a handler panics, it really shouldn't bring down the entire server. This is where `catch_panic` before calling each handler would be useful.

It would also be nice if the example-app handled cases where the value was not valid (>255, <0, or not an integer) with a 400 Bad Request extender to present a nice error page. In either case, i think a blank page (which happens now) is worse than causing the browser to show that it couldn't connect to the site or something.

**Comment by bradleybeddoes** [comment]
Couldn't agree more and was discussed prior to 0.1. Just didn't make the cut with all the things we had outstanding.

I believe the way we'll handle this is with a `Middleware` implementation that we'll recommend folks configure in their default `Pipeline`.

**Comment by coder543** [comment]
> I believe the way we'll handle this is with a Middleware implementation that we'll recommend folks configure in their default Pipeline.

Is there ever a time when someone would want their server to panic if a single request panics? It seems like something that should just be built in before each handler function is called, but that's just my opinion.

**Comment by Nokel81** [comment]
Could not this be implemented at a top level middlewear that is a try / catch that surrounds all calls bellow it?

**Comment by Nokel81** [comment]
My only concern about that is if the way Rust handles asynchronous external calls. If it pseudo-blocking then it should be fine. The main concern stems from if a try / catch would be able to catch errors within asynchronous blocks.

**Comment by smangelsdorf** [comment]
I believe this would need to be a two-part solution, to deal with panicking async code:

1. A `catch_unwind` which handles a panic in a `Handler` and/or `Middleware` below, before the `Future` is returned; and
2. A panic-catching `Future`, where `poll` would wrap the inner `Future::poll` with `catch_unwind`.

We'll have to be careful that (2) isn't a performance hit, but I've always found `catch_unwind` to be very cheap any time I've measured it.
