### ISSUE TITLE
Documentation on homepage is missing type parameters for `Box`

### ISSUE THREAD

**Issue by shepmaster** [gotham-rs/gotham#171]
The "middleware" example on the homepage is missing what's in the `Box`:

![image](https://user-images.githubusercontent.com/174509/36951073-0edb9022-1fcd-11e8-9361-c5accd29d7be.png)

I don't see *any* `<` on the page, so it seems likely to be an encoding issue somewhere.

**Comment by smangelsdorf** [comment]
Thanks for reporting this, we both missed it when reviewing the content before it went live.
