### ISSUE TITLE
Store glob match in state

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#175]
When using globs in routes and extracting path components store the component of the path which matched on the glob within the PathExtractor. Stored value will be a Vec of ordered path segments.

This will require an example showing how to do the Serde integration.

**Comment by illicitonion** [comment]
I gave this a go, and have a (pleasingly simple) working solution for the case where there's a single `*` in the route, which just populates a `Vec<String>` named `glob` if it's present in the deserialization target. Does that sound like a reasonable API?

How do we want this to work in the case of multiple `*`s in the route? a `Vec<Vec<String>>`? Multiple `Vec<String>` fields (`glob0`, `glob1`, ...)? Something else?

Also, I can't find anywhere in the documentation where `*` wildcards are specified/described. Is there documentation somewhere which I'm missing? If not, where would be a good place to document them? As far as I can tell, `*`s match as few path components as they can, i.e.
`/*/:foo/*` will match `foo=1` in `/0/1/2/3/4/5`. `/*/*/:foo/*` will match `foo=2`.

**Comment by smangelsdorf** [comment]
@illicitonion I spoke to @bradleybeddoes about this the other day, and we came up with the idea to restrict globs to only be in the tail position. It was originally implemented to be as generic as possible, but starts to sound less appealing when considering ambiguities like you've pointed out here. The router builder will need to reject non-conformant routes if we document restrictions on where globs can be used. We can probably leave the tree implementation as-is.

One positive of that idea is that only a single glob can exist for a route. The obvious downside – the loss of flexibility – is something we could worry about in the future when the need arises.

The idea I had at the time was to use `*` for the name of the field, forcing apps to give them a meaningful name like:

```rust
#[derive(Deserialize, StateData, StaticResponseExtender)]
struct MyPathParams {
    #[serde(rename = "*")]
    parts: Vec<String>,
}
```

I'm open to opinions though.

@bradleybeddoes Have you had any more thoughts on the tail position glob restriction since we last spoke about it?

**Comment by illicitonion** [comment]
Wow, the `rename` approach is nice, and Just Works out of the box with no code modifications (assuming only one glob is present). I like it!

**Comment by illicitonion** [comment]
It would also be a simple change to make something like:

```rust
#[derive(Deserialize, StateData, StaticResponseExtender)]
struct MyPathParams {
    #[serde(rename = "*0")]
    first_parts: Vec<String>,
    #[serde(rename = "*somethingelse")]
    second_parts: Vec<String>,
}

route.get("/foo/*0/bar/*somethingelse")
```

or

```rust
#[derive(Deserialize, StateData, StaticResponseExtender)]
struct MyPathParams {
    #[serde(rename = ":*0")]
    first_parts: Vec<String>,
    #[serde(rename = ":*somethingelse")]
    second_parts: Vec<String>,
}

route.get("/foo/:*0/bar/:*somethingelse")
```

or

```rust
#[derive(Deserialize, StateData, StaticResponseExtender)]
struct MyPathParams {
    #[serde(rename = ":*0")]
    first_parts: Vec<String>,
    #[serde(rename = ":*somethingelse")]
    second_parts: Vec<String>,
}

route.get("/foo/*{0}/bar/*{somethingelse}")
```

work if we're happy to specify the behaviour of `*`s more, though possible these are sufficiently less obvious to not want to do them.

**Comment by bradleybeddoes** [comment]
I like simple (i.e. `*` in the tail position only) but @illicitonion has raised a few interesting examples too.

@illicitonion are any of those "real world" scenarios you have needed on a past project?. Does anyone else have any practical usage of multiple globs in routes from their own projects that might help thinking here?

I am somewhat concerned that supporting anything other than tail may weirdly impact how we [sort nodes](https://github.com/gotham-rs/gotham/blob/master/gotham/src/router/tree/node.rs#L342) but I am sure this can be thought through. The builder would also need some [minor tweaks](https://github.com/gotham-rs/gotham/blob/master/gotham/src/router/builder/draw.rs#L809) in how it defines a `SegmentType::Glob`.

**Comment by illicitonion** [comment]
I can't think of any specific times I've needed multiple globs in the past; I can imagine cases where they may be useful, but they're all pretty contrived. Definitely happy to enforce at most one glob as a trailing pattern in the short term, and re-consider if new use cases come up :)

I can put together that restricting code on the router builder and an example (realistically probably over the weekend), but am also very happy for someone else to do so first if they have the time/desire :)

**Comment by bradleybeddoes** [comment]
Let move forward on single glob and enforcing that.

@illicitonion implementation is all yours mate 🍻

**Comment by illicitonion** [comment]
Hmm... The route builder machinery today doesn't expose any possibility of error... I don't really like any of these options:
1. Erroring all requests.
2. Silently not matching any requests if multiple globs are present.

But this doesn't seem like a big enough issue to bother changing the API over... Any thoughts?

Anywho, sent over an example: https://github.com/gotham-rs/gotham/pull/187

**Comment by whitfin** [comment]
@bradleybeddoes hi! Given that the example was merged, I'm curious if you have any thoughts on anything else we might need to include before closing this issue?
