### ISSUE TITLE
no method named `serve_connection` found for type `hyper::server::Http` in the current scope

### ISSUE THREAD

**Issue by nyarly** [gotham-rs/gotham#180]
I updated to Gotham 0.2.0 and got this error:

```rust
error[E0599]: no method named `serve_connection` found for type `hyper::server::Http` in the current scope
   --> /home/judson/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.2.0/src/test/mod.rs:172:14
    |
172 |             .serve_connection(ss, service)
    |             
```

I suspect that I need to update hyper, which suggests that Gotham doesn't report its dependency adequately?

**Comment by smangelsdorf** [comment]
Looks like this method was added in hyper 0.11.7

https://docs.rs/hyper/0.11.7/hyper/?search=serve_connection
https://docs.rs/hyper/0.11.6/hyper/?search=serve_connection

I'll look at tightening our dependency requirements to make sure this doesn't keep stinging people. Thanks for reporting it.
