### ISSUE TITLE
Composible Service

### ISSUE THREAD

**Issue by nyarly** [gotham-rs/gotham#183]
In #182 I was saying

> In a perfect world, Gotham would provide convenience start and start_tls functions, as well as a way to get a tokio_service::Service so that it could be passed to other tokio consumers (especially hyper)

Really, the core to this idea is allowing a Gotham structure to be used in a composed HTTP service provider. #182 is one use case (in effect decorating the HTTP service in the TLS protocol), but another conceivable use case would be a Rust analogue of https://golang.org/pkg/net/http/pprof/ - which would involve muxing a Gotham service with another hyper client library.

While I appreciate that GothamService as it stands is probably too large an interface to export, perhaps there could be a `tokio_service::Service` built from or wrapping a `GothamService`?

The salt to take this with is that while I'm pretty sure that would solve my immediate use case ("use with `tokio_proto` and `native_tls`") I'm not completely clear about the "mux" case.

**Comment by smangelsdorf** [comment]
This ties in with #95, in that both issues could be resolved with the same solution. I came up with a [rough idea](https://github.com/gotham-rs/gotham/issues/95#issuecomment-361544427) on how to make further progress there, but it will need a little more thought/experimentation before it suits this ticket as well.

@nyarly Does that get most of the way to what you're trying to achieve? Do you want to work on this?

The biggest gap that comes to mind is the inability to identify which `GothamListener` (to use the naming from my comment) created a connection, for example when http+https apps want to know whether a connection was secure or not.

**Comment by nyarly** [comment]
I think your comments there are in the same vein, for sure. Lemme take a swing at it, sure.

**Comment by cite-reader** [comment]
I took a look at this recently so I could plug a Gotham application into a Unix socket. The resulting branch is [here](https://github.com/cite-reader/gotham/tree/expose-service).

The tricky part is that the Service trait is only implemented for `ConnectedGothamService`, but the key feature of that struct is the `std::net::SocketAddr`. Transports that aren't IP 4 or 6 don't have that. My solution was to pull that into `GothamService` as an optional field, but I think some additional discussion is warranted before I go for a PR.

**Comment by msrd0** [comment]
This has been mostly implemented in #526, but the client address is still required. @cite-reader I feel like unix sockets could easily be implemented by faking an address, e.g. always setting it to `::1` or something similar. Would that work for you?

**Comment by cite-reader** [comment]
I instinctively distrust interfaces that try to lie rather than admit some information isn't available. Inevitably they end up confusing someone when the things they're being told don't match reality, and at best it just causes someone to get frustrated.

... That said it wouldn't have affected the use case I had a year ago, I guess.

**Comment by msrd0** [comment]
The only place I can find that gotham uses the client address internally is for the logger, but could of course be used by code outside of gotham. I'm going to close this issue, if anyone wants to make client addresses optional, I'm happy to review a PR for it.
