### ISSUE TITLE
DispatcherImpl/PipeHandleChain visibility

### ISSUE THREAD

**Issue by nyarly** [gotham-rs/gotham#184]
I'm migrating a toy service from 0.1.2 to 0.2.0, and I have

```rust
use gotham::router::route::dispatch::{PipelineHandleChain, DispatcherImpl};
```
which produces:
```
src/server/router.rs|2 col 39 error 603| trait `PipelineHandleChain` is private
||   |
|| 2 | use gotham::router::route::dispatch::{PipelineHandleChain, DispatcherImpl};
||   |                                       ^^^^^^^^^^^^^^^^^^^
|| cannot continue compilation due to previous error
```

But `DispatcherImpl::new` receives a `PipelineHandleChain`, which significantly reduces its utility. For instance:

```rust
fn static_route<NH, P, C>(
  methods: Vec<Method>,
  new_handler: NH,
  active_pipelines: C,
  ps: PipelineSet<P>) -> Box<Route + Send + Sync>
  where NH: NewHandler + 'static,
        C: PipelineHandleChain<P> + Send + Sync + 'static,
        P: Send + Sync + 'static
{
  let matcher = MethodOnlyRouteMatcher::new(methods);
  let dispatcher = DispatcherImpl::new(new_handler, active_pipelines, ps);
  let extractors: Extractors<NoopPathExtractor, NoopQueryStringExtractor> = Extractors::new();
  let route = RouteImpl::new(
    matcher,
    Box::new(dispatcher),
    extractors,
    Delegation::Internal);
  Box::new(route)
}
```

which worked in 0.1.2

**Comment by nyarly** [comment]
I'm pretty sure the solution in my case will be to translate this into the new route building interface, but a public method that receives a private type is an irritation.

**Comment by bradleybeddoes** [comment]
Seems like a pretty straight forward "lets fix this" @nyarly.

Could you propose a PR against `0.2-maint` branch that addresses this? We're getting ready for a 0.2.1 to fix up a few rough edges like this.

**Comment by smangelsdorf** [comment]
This is a misleading compile error, the trait is still public but has been moved to [`gotham::pipeline::chain::PipelineHandleChain`](https://docs.rs/gotham/0.2.0/gotham/pipeline/chain/trait.PipelineHandleChain.html). It's imported and used in the `gotham::router::route::dispatch` module, which is why it's reported as a private member there.
