### ISSUE TITLE
Add better rustdoc example code for `with_pipeline_chain` in the router builder

### ISSUE THREAD

**Issue by smangelsdorf** [gotham-rs/gotham#190]
The current example only shows how to switch to using _no_ pipelines, but not how to use a different set of pipelines. We need a second doc example showing how to use multiple pipelines for a subset of routes (that's the whole point of pipelines, after all).

Something I knocked together quickly but didn't test:

https://gist.github.com/smangelsdorf/eb0d15dbad2697b3ad1f5808bf114993

**Comment by ParisLiakos** [comment]
@smangelsdorf this can be closed now, right?

**Comment by smangelsdorf** [comment]
It can. Good catch 👍
