### ISSUE TITLE
Integrate AppVeyor

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#2]
Per our previous CI environment this should build with Rust stable, beta and nightly.

If possible the two releases prior to the current stable Rust also.

As part of this ticket Cargo.toml should be updated with AppVeyor badges.

**Comment by smangelsdorf** [comment]
We have AppVeyor integrated, but it's only building with stable Rust currently. Leaving this open for now.

**Comment by bradleybeddoes** [comment]
Thoughts on this a few months later @smangelsdorf?

Perhaps stable only is "good enough" for Windows (and other future target platform we might consider that doesn't see as much usage os *nix?).

**Comment by smangelsdorf** [comment]
Yeah, I tend to agree. It seems pretty unlikely that we'll have platform-specific breakage on nightly Rust.
