### ISSUE TITLE
gotham.rs - NXDOMAIN

### ISSUE THREAD

**Issue by im-0** [gotham-rs/gotham#219]
```
$ nslookup gotham.rs 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find gotham.rs: NXDOMAIN
```

It seems that your domain name is expired or something.

Site is still working, it is possible to access it by adding the last known IP into `/etc/hosts`:

```
104.27.172.247 gotham.rs
```

**Comment by bradleybeddoes** [comment]
Thanks for this alert.

The domain had expired in the last 24h due to reminders going to a defunct mail address.

Have sorted that payment out, should come back up in the next hour or two.

**Comment by smangelsdorf** [comment]
Confirmed it's back up and running now 👍

**Comment by bradleybeddoes** [comment]
Corrected

```
;; ANSWER SECTION:
gotham.rs.		299	IN	A	104.27.172.247
gotham.rs.		299	IN	A	104.27.173.247

;; Query time: 171 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon May 07 21:02:41 AEST 2018
;; MSG SIZE  rcvd: 70
```
