### ISSUE TITLE
Is there any way to gracefully terminate the event loop?

### ISSUE THREAD

**Issue by im-0** [gotham-rs/gotham#220]
I need to do some additional cleanup actions after gotham::start(). So it would be very good if there is a way to make it exit. For example, using custom SIGTERM handler (tokio-signal) with some glue code.

**Comment by ChristophWurst** [comment]
A possible solution would be to expose the Hyper `run_until` API in Gotham, too: https://docs.rs/hyper/0.11.26/hyper/server/struct.Server.html#method.run_until

**Comment by nyarly** [comment]
#310 includes @im-0's  example, updated to modern Tokio/Hyper, that demonstrates how to do this.
