### ISSUE TITLE
How to return html page, in particular a Tera template, from an action?

### ISSUE THREAD

**Issue by GildedHonour** [gotham-rs/gotham#224]
I haven't found an example of how to work with html in gotham, is there any?

**Comment by bradleybeddoes** [comment]
We don't yet have an example of this however the general approach would be to have your templating crate of choice do whatever rendering/transformation to data you'd like via whatever API they expose and then use [create_response](https://docs.rs/gotham/0.2.1/gotham/http/response/fn.create_response.html) as you shown in many of the examples.
