### ISSUE TITLE
Router creation enhancements

### ISSUE THREAD

**Issue by bradleybeddoes** [gotham-rs/gotham#24]
For the 0.1 release of Gotham the `Router` API is reasonably verbose. 

This is necessitated by the need to set up all the components the `Router` expects to see for each `Route` and is further complicated, to some degree, by the underlying data structure that the `Router` uses.

The good news is that this can be simplified by adding a layer of code that is specifically targetted at easing construction, the `Router` itself does not need any major change.

The end goal is to get reasonably close to what [Rails](http://guides.rubyonrails.org/routing.html) and [Phoenix](https://hexdocs.pm/phoenix/routing.html) offers application developers whilst maintaining type safety and compiler guarantees.

#7 should be taken into consideration as part of this work as any builder/macro implementation will likely need to be adapted again to suit this need.

**Comment by smangelsdorf** [comment]
I'm experimenting with this now. Will post an update when I've made a bit of progress.

**Comment by ChristophWurst** [comment]
> The end goal is to get reasonably close to what Rails and Phoenix offers application developers whilst maintaining type safety and compiler guarantees.

Not sure how that could be possible with Rust. I'm not familiar with  Rails/Phoenix, but from those documentations it looks stingly-typed and reflective. We don't really have that in Rust, do we?

The [iron framework router](https://github.com/iron/router#example) seems to have a clean and simple API too. That could be used as inspiration.

**Comment by bradleybeddoes** [comment]
Hey @ChristophWurst I put this up on [Gitter](https://gitter.im/gotham-rs/gotham) as well but the good news is there is a branch @smangelsdorf has which we've started exploring concepts for the router using the builder pattern. He's going to get that pushed so we can discuss publicly.

In addition to the builder pattern offering we're thinking a set of macros (for folks that like to use those) which live on top of whatever builder api we settle on will be one way we can get close(ish?) to how Rails/Phoenix defines their routes.

**Comment by bradleybeddoes** [comment]
Closed by https://github.com/gotham-rs/gotham/pull/70
