### ISSUE TITLE
Remove need for Vec allocation in Response body

### ISSUE THREAD

**Issue by whitfin** [gotham-rs/gotham#244]
Gotham is quite slow in benchmarks (relatively), and one of the big reasons is that the response body as it stands must be `Vec<u8>`. This means that even the simplest "hello world" cannot exist without an allocation. We should use some sort of trait to remove this allocation, to allow things like `&[u8]` and `&'static str` which would provide better ergonomics and also better performance when allocation is not needed.

**Comment by jxs** [comment]
I can try to work on this one, but since Hyper changed it's response from 0.11 to 0.12 this should wait until the update it's merged

**Comment by whitfin** [comment]
@jxs agreed!

**Comment by whitfin** [comment]
Note to self; we should also `impl IntoResponse<T>` for all `T` types from stdlib that make sense (`String`, `str`, etc.).
