### ISSUE TITLE
Middleware that parses the request body and if successful call chain (Question)

### ISSUE THREAD

**Issue by nater540** [gotham-rs/gotham#248]
_Please bare with me here since I'm **extremely** new to Rust programming!_

I am attempting to create a Gotham middleware for GraphQL (using Juniper) that does the following:
1) Grab the request body & parse it as JSON.
2) If the body was parsed correctly, do GraphQL logic which gets stored into the request state, then call the `chain(state)` method to continue processing the request.
3) If the body was **not** parsed correctly, return a `StatusCode::UnprocessableEntity`.

This is what I've come up with so far (which does not work)

```rust
impl Middleware for ExampleMiddleware {
  fn call<Chain>(self, mut state: State, chain: Chain) -> Box<HandlerFuture>
    where Chain: FnOnce(State) -> Box<HandlerFuture> {

    Body::borrow_from(&mut state)
      .concat2()
      .then(|res| match res {
        Ok(body) => {
          let body_contents = String::from_utf8(body.to_vec()).unwrap();

          // TODO: Parse the body_contents as json and do further processing

          (state, chain(state))
        }
        Err(err) => {
          (state, HandlerError::with_status(err.into_handler_error(), StatusCode::UnprocessableEntity))
        }
      })
  }
}
```

My question is, what would be the proper way of receiving the entire request body, performing logic on it, and if successful calling the request chain for further processing -- if any of that fails, returning a clean error to the client.

**Comment by jxs** [comment]
Hi @nater540,
for the code to compile, You need to return `Box<HandlerFuture>`  from both match match arms, and then return the resulting future, eg:

```rust
impl Middleware for ExampleMiddleware {
    fn call<Chain>(self, mut state: State, chain: Chain) -> Box<HandlerFuture>
    where
        Chain: FnOnce(State) -> Box<HandlerFuture> + 'static,
    {
        let p = Body::take_from(&mut state)
            .concat2()
            .then(|res| match res {
                Ok(body) => {
                    let body_contents = String::from_utf8(body.to_vec()).unwrap();

                    // TODO: Parse the body_contents as json and do further processing

                    chain(state)
                }
                Err(err) => Box::new(future::err((state, HandlerError::with_status(
                    err.into_handler_error(),
                    StatusCode::UnprocessableEntity,
                ))))
            });
        Box::new(p)
   }
}

```
