### ISSUE TITLE
Middleware for specific routes

### ISSUE THREAD

**Issue by biot023** [gotham-rs/gotham#258]
Hi -- I've literally just finished The Rust Book tonight, so my apologies if I'm missing anything really obvious.
I was wondering if it's possible to specify middleware for some routes but not others?
I guess maybe by nesting calls to `build_router(...)` or something like that?
It'd be good to have middleware check credentials for some routes, for instance, and not for others.
Thanks,
   Doug.

**Comment by biot023** [comment]
Might this be done with `gotham::pipeline::set`?
With different handles applied to different routes in the router?
I'll keep investigating but if anyone had an example of this they could point me to, I'd be really grateful!
(Or if I'm barking up completely the wrong tree, like I was in my other question, please do let me know!)
Thanks,
   Doug.

**Comment by colinbankier** [comment]
Hi @biot023 - thanks for your interest in Gotham :)
It certainly is possible - you would define multiple `pipeline`s into a `pipeline_set`. Unfortunately I don't see a good example in the examples section, but this is a good trigger for us to create one.
Have a look around https://docs.rs/gotham/0.2.1/gotham/pipeline/index.html - let us know if you can figure it out from there - and we can build out examples for such use cases for the future.

**Comment by colinbankier** [comment]
Hi @biot023 - turns out there is a good example amongst the docs that I had missed: https://docs.rs/gotham/0.2.1/gotham/router/builder/trait.DrawRoutes.html#method.with_pipeline_chain

Let me know if that solves your use case.

**Comment by biot023** [comment]
Brilliant, thank you @colinbankier !
I'll have a look my next free evening this week (it's a side project) and let you know how I get on.
Thanks so much for digging both of those links out for me!

**Comment by biot023** [comment]
Hi again @colinbankier 
Sorry it's taken me a while to get back to this -- pressures of work and all!
I've been trying to implement something using this yesterday and today but I'm obviously not getting some concepts.
The example you gave shows how to route without the defined pipelines but not how to construct an alternate set to use.
I don't see how I can construct a pipeline set and chain, sorry, and digging through the code isn't getting me anywhere.
Part of the problem is that I don't understand where the chain comes from or even what it is. Which I guess means that I must not understand the pipeline set, either.
Would you be able to help me with these questions:

* How would I create two different piplelines, one using (Middleware1 and Middleware2) and the other using (Middleware1 and Middleware3)?
* How do I create a chain to use in `build_router` that would use both of these pipelines?
* And how would I use the different pipelines for different routes? With `with_pipeline_chain(pipeline1, |route| {...})` ?

I hope I'm not being too dense. No doubt I'll be smacking my forehead once I realise what I'm supposed to be doing. ;)
Thanks very much for your help,
   Doug.

**Comment by nyarly** [comment]
Hey, @biot023 are you looking to do something like https://github.com/nyarly/d2tools/blob/master/src/server/router.rs#L24-L30 ?

**Comment by biot023** [comment]
@nyarly 
That definitely looks like it might be the sort of thing!
I should get a chance to have a play with that in the next evening or two and I'll feed back -- thanks so much!

**Comment by colinbankier** [comment]
Thanks for the example @nyarly 
Using that, I built out a little sample for the scenario you described @biot023 

```
  let ps_builder = new_pipeline_set();
  let (ps_builder, p1) = ps_builder.add(new_pipeline()
    .add(Middleware1)
    .add(Middleware2)
    .build());
  let (ps_builder, p2) = ps_builder.add(new_pipeline()
    .add(Middleware1)
    .add(Middleware3)
    .build());
  let ps = finalize_pipeline_set(ps_builder);

  let pipeline1 = (p1, ());
  let pipeline2 = (p2, ());

  build_router(pipeline1, ps, |route| {
    route.get("/path1").to(handler);
    route.with_pipeline_chain(pipeline2, |route| {
      route.get("/path2").to(handler);
    });
  })
```

You can also mount totally independent routers to achieve a similar thing

```
    let (chain1, pipelines1) = single_pipeline(
        new_pipeline()
        .add(Middleware1)
        .add(Middleware2).build());

    let (chain2, pipelines2) = single_pipeline(
        new_pipeline()
        .add(Middleware1)
        .add(Middleware3).build());

    let router1 = build_router(chain1, pipelines1, |route| {
            route.get("/").to(handler);
        });
    let router2 = build_router(chain2, pipelines2, |route| {
            route.get("/").to(handler);
        });

    build_simple_router(|route| {
        route.delegate("/path1").to_router(router1);
        route.delegate("/path2").to_router(router2);
    })
```

In general I think the contortions required to build the pipelines is something we could improve the ergonomics of.

**Comment by biot023** [comment]
@colinbankier 
Ah, brilliant, thank you! I think I like the clearer nature of your second example the most -- I think I'll try to work to that.
Thanks so much for everyone's help.
   Doug.

**Comment by biot023** [comment]
That second approach seems to be working well. I'll mark this as closed once I'm certain it works as I think it should. I've hit a couple of other roadblocks so it might be a day or two!
Thanks again!
   Doug.

**Comment by colinbankier** [comment]
@biot023 - I assume this issue can be closed now? I'll close it - but feel free to re-open if you have ongoing issues with the examples above.
