### ISSUE TITLE
Handler struct with ref to another struct?

### ISSUE THREAD

**Issue by biot023** [gotham-rs/gotham#259]
I'm trying to create a handler that can access a ref to a config object but I'm entering a world of lifetime pain!

The handler looks something like this:

```
pub struct VersionHandler<'a> {
    config: &'a Config,
}
impl<'a> VersionHandler<'a> {
    pub fn with_config(config: &'a Config) -> VersionHandler<'a> {
        VersionHandler { config }
    }
}
```

It has the necessary traits derived or implemented on it.

However, when I try to use it in my routes:

```
fn router<'a>(config: &'a Config) -> Router {
    build_simple_router(|route| {
        route.get("/version").to(VersionHandler::with_config(config));
    })
}
```

I get this error:

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
  --> src/lib.rs:19:34           
   |                            
19 |         route.get("/version").to(handlers::VersionHandler::with_config(config));
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                
   |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the function body at 15:1...
  --> src/lib.rs:15:1                                            
   |                                  
15 | fn router<'a>(config: &'a Config) -> Router {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                     
note: ...so that reference does not outlive borrowed content       
  --> src/lib.rs:19:72                       
   |                                                                  
19 |         route.get("/version").to(handlers::VersionHandler::with_config(config));
   |                                                                        ^^^^^^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the type `handlers::VersionHandler<'_>` will meet its required lifetime bounds
  --> src/lib.rs:19:31                                           
   |  
19 |         route.get("/version").to(handlers::VersionHandler::with_config(config));
   |                               ^^                 
                                                                              
error: aborting due to previous error             

```

I've tried monkeying around with all sorts, including lifetime subtypes on the handler struct and everything, but all to no avail.
I looked in the source code for when handlers are assigned to routes and it mentions the `'static` lifetime there. Does this mean that what I want to do is only possible if the `Config` struct instance is static, too?
Is what I want to achieve even possible?
Thanks in advance for any and all help -- I can't help feeling that I've jumped in at the deep end, rather! :)
   Doug.

**Comment by whitfin** [comment]
@biot023 I've never done this before, so I'm not entirely sure it's the correct way to go about it. You would usually use a middleware to contain any state.

In your case, what happens if you just clone out the config? And avoid any lifetimes so it's all self contained?

**Comment by biot023** [comment]
Cheers @whitfin 
I've made the config object static but am now facing another obscure error when I try to...
You know what?

> You would usually use a middleware to contain any state.

That's my answer!
Cheers, man!
