### ISSUE TITLE
Add an example of how to customize error responses with a finalizer.

### ISSUE THREAD

**Issue by colinbankier** [gotham-rs/gotham#260]
There currently seems to be no example of how to customize the response for 404, 500 etc.
Finalizers exist for this purpose, https://github.com/gotham-rs/gotham/blob/master/gotham/src/router/response/finalizer.rs.

This issue is to add an example of how to use them.

**Comment by TyberiusPrime** [comment]
I'm willing to submit a PR if somebody can tell me how to replace/extend the body in the ResponseExtender<Body>.extend method.

**Comment by TyberiusPrime** [comment]
I figured it out, PR is up.
