### ISSUE TITLE
Accessing the response code (for logging)

### ISSUE THREAD

**Issue by biot023** [gotham-rs/gotham#262]
Hi -- how would I access the response code for logging?
Currently I'm trying to call this in some logging middleware:

```
fn log_response(&self, res: &Box<HandlerFuture>) {   
    match *res {                                     
        HandlerFuture::Item(ref state, ref res) => { 
            let rid = request_id(state);             
            info!(self.logger, "{}: OK", rid);       
        },                                           
        HandlerFuture::Error(ref state, ref err) => {
            let rid = request_id(state);             
            error!(self.logger, "{}: Error!", rid);  
        },                                           
    }                                                
}                                                    
```
But this gives me this error:

>     Checking dp-be v0.1.0 (file:///home/me/work/home/rust/dp/be)
> error[E0599]: no associated item named `Item` found for type `futures::Future<Item=(gotham::state::State, hyper::Response), Error=(gotham::state::State, gotham::handler::HandlerError)> + 'static` in the current scope
>   --> src/middlewares/logging.rs:35:13
>    |
> 35 |             HandlerFuture::Item(ref state, ref res) => {
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ associated item not found in `futures::Future<Item=(gotham::state::State, hyper::Response), Error=(gotham::state::State, gotham::handler::HandlerError)> + 'static`
> 
> error[E0599]: no associated item named `Error` found for type `futures::Future<Item=(gotham::state::State, hyper::Response), Error=(gotham::state::State, gotham::handler::HandlerError)> + 'static` in the current scope
>   --> src/middlewares/logging.rs:39:13
>    |
> 39 |             HandlerFuture::Error(ref state, ref err) => {
>    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ associated item not found in `futures::Future<Item=(gotham::state::State, hyper::Response), Error=(gotham::state::State, gotham::handler::HandlerError)> + 'static`
> 
> error: aborting due to 2 previous errors
> 
> For more information about this error, try `rustc --explain E0599`.
> error: Could not compile `dp-be`.
> 

Which is rather above my current pay grade in Rust!
I'm not even sure how to check that I'm using the right objects in the match clause.
Is the issue that I'm dealing with a future that doesn't know anything about itself until it is resolved?
How would I ever know what to log if that is the case?
Any and all help is *very* gratefully received!
Thank you,
   Doug.

**Comment by whitfin** [comment]
You can look at [this PR](https://github.com/gotham-rs/gotham/pull/221) for an example of how to hook a middleware into a response to act as a logger. Let me know if you need any further guidance!

**Comment by biot023** [comment]
Hi -- thanks @whitfin !
Sorry I've not looked at this yet -- I'm a n00b to both Rust and Gotham.rs so my progress is fitful at best!

**Comment by whitfin** [comment]
@biot023 no worries; let me know if you need anything. You can always join us on Gitter, or in #gotham on the Rust Slack.

**Comment by whitfin** [comment]
@biot023 Hi! Just wondering if you've made any progress here; if you need any more help, or if this issue is good to be closed?

**Comment by colinbankier** [comment]
Hi @biot023 - this issue seems stale, so I'll close it for now. If you need further help feel free to reopen it or to reach out on gitter (https://gitter.im/gotham-rs/gotham).
