### ISSUE TITLE
Any handy hints for getting around RefUnwindSafe trait bound failures?

### ISSUE THREAD

**Issue by biot023** [gotham-rs/gotham#266]
Hi -- I have a core client object that uses `Box<T>`s and things like that to hold values and other objects.
And when I try to create a middleware that contains a passed-in (cloned) instance of the client object I'm getting the error:

> error[E0277]: the trait bound `r2d2::HandleError<r2d2_diesel::Error> + 'static: std::panic::RefUnwindSafe is not satisfied in `middlewares::core::Mw`

(The client object uses diesel and r2d2 and things.)
Can I just implement `RefUnwindSafe` for my client object?
Does anyone have any handy hints as to how to get around this?
Or maybe pointers at further reading? I'm getting the impression that I'm rather beyond the territory mapped out by the Rust book, here, and maybe out of my depth, so sorry I'm spamming the issues. :)
Thanks,
   Doug.

**Comment by msrd0** [comment]
I don't think manually implementing `RefUnwindSafe` is a good idea as it should be auto-implemented for all types that can survive a panic/unwind. I'd start by reading [the `RefUnwindSafe` documentation](https://doc.rust-lang.org/stable/std/panic/trait.RefUnwindSafe.html) if you want to know more.

**Comment by ar3s3ru** [comment]
Sorry @msrd0 but you haven't provided any information about this issue, and the `RefUnwindSafe` doesn't provide any useful information, so I wouldn't close the issue just yet.

I understand that the `RefUnwindSafe` marker is required to prevent panics in one future to bring down the whole application, but many components out there we'd like to put in the `State` with `StateMiddleware` are going to have some degree of internal mutability. How do we deal with that? In my case, this is a huge blocker for adopting the library.

Thanks

**Comment by msrd0** [comment]
Well, I'm not going to reiterate the concept of panics and unwinding them, the gotham issue tracker doesn't seem to be the place for general rust concepts (and I only understood them to some degree myself).

However, I don't understand what you are trying to acchieve. As outlined in the `StateMiddleware` documentation, your custom type will likely be cloned. The `Clone` implementation of `Cell` ([source](https://doc.rust-lang.org/stable/src/core/cell.rs.html#243-248)) does not seem to keep mutability in the way you might expect, so your changes will unlikely survive long. In that case, just use `borrow_mut` or `take_mut` from the state. Other data structures that are designed for multi-threaded mutability like `Arc` already [implement `RefUnwindSafe`](https://doc.rust-lang.org/stable/std/sync/struct.Arc.html#impl-RefUnwindSafe).

So I think this issue should remain closed, if you have a more concrete and gotham-related question, please open a new issue. And regarding the original question with r2d2 and diesel, we have a [middleware for that already](https://docs.rs/gotham_middleware_diesel/0.2.0/gotham_middleware_diesel/).
