### ISSUE TITLE
Default headers are not being correctly attached

### ISSUE THREAD

**Issue by whitfin** [gotham-rs/gotham#269]
This broke during the Hyper 0.12 adoption; the default headers (via `set_headers`) in the response module are no longer being set on responses. This should be fixed prior to v0.3 to avoid breaking the headers contract.

**Comment by colinbankier** [comment]
Should be an easy fix, I noticed that in `helpers/http/response/mod.rs` there is a comment that says 

> `extend_response` delegates to `set_headers` for setting security headers.

Yet, `set_headers` is never called. Should be trivial to add a call back in.

**Comment by smvoss** [comment]
Is this by chance the same thing stopping the "Hello world" example (taken from website) from working?

I see the following when attempting to run it:
```
error[E0243]: wrong number of type arguments: expected 1, found 0
  --> src/main.rs:17:43
   |
17 | pub fn say_hello(state: State) -> (State, Response) {
   |                                           ^^^^^^^^ expected 1 type argument

error: aborting due to previous error
```

**Comment by colinbankier** [comment]
@smvoss - this is a different issue - but it is a good point that the website is out of date.
`master` is currently working towards the 0.3 release, which will have breaking changes due to the hyper upgrade. 0.2 is still the latest "release" until then.
If you're looking for examples that work with master - all examples in the "examples" directory compile and work - so this is a better place to look until 0.3 is released.

**Comment by smvoss** [comment]
@colinbankier I was using the `0.2.1` release from cargo, not building off of master

**Comment by whitfin** [comment]
@smvoss are you certain that's the case? If so, perhaps you have Hyper 0.12 in your dependencies rather than 0.11?

**Comment by smvoss** [comment]
Ah, I believe I did have hyper 0.12 it likely just grabbed newest. I didn't see any requirements on which to use on the website, so I didn't think anything of it

**Comment by whitfin** [comment]
I'm currently working on a small refactoring in this module anyway; so I'll try pick this up there. I do think that perhaps these headers should be some sort of built-in middleware, to allow them to be optional.
