### ISSUE TITLE
Could not find `helpers` in `gotham`

### ISSUE THREAD

**Issue by crusty-dave** [gotham-rs/gotham#273]
Many examples are using this:

` use gotham::helpers::http::response::create_empty_response;
`
However, it doesn't compile:

```
error[E0433]: failed to resolve. Could not find `helpers` in `gotham`
  --> src\cso_server.rs:11:13
   |
11 | use gotham::helpers::http::response::create_empty_response;
   |             ^^^^^^^ Could not find `helpers` in `gotham`

```

Note that create_response() is actually here:

`use gotham::http::response::create_response;
`

But that doesn't work for create_empty_response().

```
error[E0432]: unresolved import `gotham::http::response::create_empty_response`
  --> src\cso_server.rs:11:5
   |
11 | use gotham::http::response::create_empty_response;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `create_empty_response` in `http::response`. Did you mean to use `create_response`?

```

I would prefer the helper function, but I can work around it.

**Comment by whitfin** [comment]
@crusty-dave if you're looking at examples on master, they're not yet released :) You should check out the examples on the v0.2.1 branch.

**Comment by crusty-dave** [comment]
@whitfin - thanks, didn't realize I was looking at master until you mentioned it! :)

**Comment by crusty-dave** [comment]
@whitfin I closed it, thanks.

If you get a chance would you look at my question on reddit?

[Changing header value while using Gotham::request_data example](https://www.reddit.com/r/learnrust/comments/9gi1yu/changing_header_value_while_using_gothamrequest/)

I have abandoned Gotham at this point and gone back to using actix-web.
