### ISSUE TITLE
JWT Middleware in Core

### ISSUE THREAD

**Issue by secretfader** [gotham-rs/gotham#289]
I've been developing an authentication middleware for Gotham 0.3 that [extracts, parses, and validates JSON Web Tokens when provided via the `Authorization` header](/uptimeventures/gotham-middleware-jwt).

Since this seems like pretty standard tooling for most web apps and APIs, I'd like to propose moving my crate to this repository. What do you think? Does it belong in the core repository, or just in the @gotham-rs org? Or is it better left at the current org? 

I'm open to suggestions, including amending the license (if need be). The bottom line is I'd like to place the code in a more community-friendly place, where it might pick up other maintainers who can step in when I'm out.

**Comment by colinbankier** [comment]
Thanks for sharing your middleware @secretfader!  I agree we certainly want to make it easy for common tooling to be discovered and maintained, and to encourage the Gotham ecosystem to grow. I'll wait for @whitfin and @nyarly to weigh in on whether they think moving this into core is the right move.

**Comment by secretfader** [comment]
Sounds good, @colinbankier. The project recently received an update enabling support for Gotham 0.3, and JWT 5.x, so all dependencies are currently up-to-date.

My initial thought was this middleware *didn't belong* in this repository, but then I realized authentication is roughly on the level of the Diesel middleware (in terms of common development practices and conveniences that speed building an app).

I'll keep an eye on this issue to see what is decided.

**Comment by secretfader** [comment]
This issue has been open for a couple months. @nyarly, @whitfin, and @colinbankier, if any of you want to continue the discussion, feel free to re-open. Otherwise, I'll close it to keep your queue of work tidy.

**Comment by colinbankier** [comment]
Thanks @secretfader. Yeah, I acknowledge activity has been pretty slow over the holiday period. Sorry about that.
I for one would vote for bringing this in, as JWT auth seems like a pretty common piece of functionality.
Feel free to open a PR with it :)

**Comment by secretfader** [comment]
I'll send you a PR later on then, and we can discuss how to allow releases by the Gotham Core Team.
