### ISSUE TITLE
The gotham 0.3 announcement example is incorrect

### ISSUE THREAD

**Issue by crusty-dave** [gotham-rs/gotham#303]
[announcement](https://gotham.rs/blog/release/2018/10/29/gotham-0.3.html)

The following:

```
    // create the response
    let body = (message, mime::TEXT_PLAIN);
    let res = create_response(&state, StatusCode::OK, body);

```
should be as follows:

```
    // create the response
    let res = create_response(&state, StatusCode::OK, body, mime::TEXT_PLAIN, message);

```

**Comment by secretfader** [comment]
This issue concerns the Gotham.rs website (rather than examples in the primary repo) and probably should be filed against the website repo at @gotham-rs/gotham.rs.

**Comment by secretfader** [comment]
I updated the blog entry in [@gotham-rs/gotham.rs#12](https://github.com/gotham-rs/gotham.rs/pulls/12). Once again, thanks for the report @crusty-dave!
