### ISSUE TITLE
Migrate to Rust 2018 Edition

### ISSUE THREAD

**Issue by whitfin** [gotham-rs/gotham#304]
Since this is now stable and the default behaviour of Cargo, we should probably update all examples to Rust 2018.

Whether we do this for the repository itself could be debated, but I can't think of a reason why not off the top of my head. If we do, I'm not sure if that should be a 0.4 though, as technically it can be breaking for people on an older version of stable.

**Comment by secretfader** [comment]
Echoing my comments from chat, I'm very much in favor of adopting Rust 2018 across the entire Gotham codebase. Our JWT middleware integration is already built with the [2018 edition](https://github.com/gotham-rs/gotham/blob/master/middleware/jwt/Cargo.toml#L15).

When updating Gotham to the latest Rust standards, I tried to thread the needle between compatibility with the 2015 edition while attempting to improve performance and memory utilization where possible. Adopting the 2018 edition as our official code standard would open the door to other improvements.

**Comment by whitfin** [comment]
I think I'll assign this to myself. I have some time this weekend to pick it up and get a PR in :)

**Comment by 0xpr03** [comment]
Not sure how your approach to versioning is, but if it breaks existing code it should be a major version increase, according to [semver](https://semver.org/)

**Comment by whitfin** [comment]
@0xpr03 it shouldn't break existing code. Even if it does, SemVer explicitly reserves pre 1.0 for breaking changes (i.e. there are no promises involved prior to 1.0).

**Comment by 0xpr03** [comment]
Then pardon the interruption. I'm actually glad to have missed this.

**Comment by whitfin** [comment]
This was actually covered in https://github.com/gotham-rs/gotham/pull/305 and I forgot to update this issue :)
