### ISSUE TITLE
Release 0.3 minor version with cookie 1.12

### ISSUE THREAD

**Issue by fabianfreyer** [gotham-rs/gotham#320]
Hi! Would it be possible to release a minor release of 0.3 that includes cookie 1.12? This would fix some issues in askama (see https://github.com/djc/askama/pull/234)

**Comment by djc** [comment]
+1. I'd be happy to help out if you guys can do a release either as a small bump from the 0.3.0 tag or from master -- I'd really like to release an Askama version that can support Actix 1.0, though.

**Comment by colinbankier** [comment]
Thanks @fabianfreyer @djc . We have a release planned imminently anyway (master already has latest cookie version) - so that will sort this out :). We'll comment back here when that is out.

**Comment by djc** [comment]
"Imminent" is now a month ago. Can you say more about the time frame? I might consider temporarily removing Gotham support if the project cannot stay in sync with the rest of the ecosystem.

**Comment by colinbankier** [comment]
Fair comment. I didn't quite expect it would turn out to be a month. It was planned for several days ago - AFAIK everything is ready to go, so I expect within a couple of days. @nyarly @whitfin please comment if you don't think you'll be able to cut the release in the next couple of days.

**Comment by colinbankier** [comment]
Sorry for the delay here - 0.4 release is now out: https://gotham.rs/blog/release/2019/07/14/gotham-0.4.html
