### ISSUE TITLE
How to achieve Content Negotiation?

### ISSUE THREAD

**Issue by mknet** [gotham-rs/gotham#326]
I'm just wondering if there are any concrete thoughts about [Content Negotiation ](https://en.wikipedia.org/wiki/Content_negotiation).
The basic idea would be that I can implement different "converters" based on the HTTP Header "Accept" so the client could ask for `application/json` or e.g. `application/xml`.
The idea is also mentioned by @onelson in #196.

As I understand the idea behind IntoResponse just one format is possible for now.
Any thoughts on that?

**Comment by colinbankier** [comment]
Thanks for the interest in gotham @mknet .
The `into_response` method takes the `State` as a param - so I guess you could check the request headers in there and build a response accordingly. Maybe some helper functions to make this easy could be included in gotham. I'm not sure if this gets you what you need? It would seem more convenient to me than having to define separate routes (as suggested in #196)  - but maybe I'm missing something.
I'm not aware of any concrete plans around Content Negotiation - but we're very open to suggestions, or ideas from other frameworks.

**Comment by mknet** [comment]
Thx fro the hint, @colinbankier. Since from my perspective the decision regarding the data format had to be made before entering the `into_response`  trait, I haven't thought of that, yet. But you are right. It could be an option to establish some generic solution used in the impl. I'll give it a try and will comment my lessons learned in here.
If you like to, you can close the issue fore now.
