### ISSUE TITLE
Unable to receive multiple cookies

### ISSUE THREAD

**Issue by 8176135** [gotham-rs/gotham#330]
Using gotham `0.4.0` on crates.io

When doing the [cookie example](https://github.com/gotham-rs/gotham/tree/master/examples/cookies/introduction), the `CookieParser` seems unable to separate out multiple cookies?

E.g.
```
let temp = CookieJar::borrow_from(&state);
dbg!(&temp);
```

when given multiple cookies will output 

```
[src\main.rs:19] &temp = CookieJar {
    original_cookies: {
        DeltaCookie {
            cookie: Cookie {
                cookie_string: Some(
                    "othercookie=foobar; adjective=repeat;",
                ),
                name: Indexed(
                    0,
                    6,
                ),
                value: Indexed(
                    7,
                    13,
                ),
                expires: None,
                max_age: None,
                domain: None,
                path: None,
                secure: None,
                http_only: None,
                same_site: None,
            },
            removed: false,
        },
    },
    delta_cookies: {},
}
```

it seems like cookie parser doesn't separate out the cookies, leading it to only recognize the first cookie?

I just started with gotham, so I might be missing something here.

**Comment by whitfin** [comment]
@8176135 that's purely the debug information, because the cookies are lazily fetched. Once you have the `CookieJar`, you can then call `jar.get("adjective")` (shown [here](https://github.com/gotham-rs/gotham/blob/master/examples/cookies/introduction/src/main.rs#L28)) to get a specific value back.

**Comment by 8176135** [comment]
I only started reading the debug information because get didn't work when there are multiple cookies (only worked for the first cookie). Try calling `jar.iter().collect()` and then debugging that output. You can see that only one cookie is in the output array.

**Comment by whitfin** [comment]
@8176135 you're right! I'll have a patch in shortly.
