### ISSUE TITLE
How to extract data from a POST body

### ISSUE THREAD

**Issue by 8176135** [gotham-rs/gotham#336]
Can someone give me a basic example of getting body data out of state? (i.e. as a `Vec<u8>` or similar)

The POST example issue #114 doesn't seem to have had any updates for a year.

**Comment by colinbankier** [comment]
Hi @8176135 .
There is an example decoding form data from a request body at https://github.com/gotham-rs/gotham/tree/master/examples/handlers/form_urlencoded

Let us know if that gives you what you need :)

**Comment by 8176135** [comment]
Ah, that seems to be what I'm looking for, thanks!
