### ISSUE TITLE
How to get request path in middleware

### ISSUE THREAD

**Issue by PrivateRookie** [gotham-rs/gotham#339]
I am trying write a middleware which is scoped by request path, but I stuck in getting request path from state, is there any doc about getting request info from state?

**Comment by colinbankier** [comment]
Hi @PrivateRookie - does this example help you out? 
https://github.com/gotham-rs/gotham/blob/master/examples/handlers/request_data/src/main.rs#L20
Basically  `let uri = Uri::borrow_from(state);` to get the URI from state.

**Comment by PrivateRookie** [comment]
That's what I what, Thank you @colinbankier . Looks like I have to read more doc about hyper :)
