### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by dns2utf8** [gotham-rs/gotham#353]
Hi all

Is it possible to use a WebSocket with gotham?

Cheers,
Stefan

**Comment by colinbankier** [comment]
Hi @dns2utf8  - WebSockets are not directly supported yet, but is certainly something we hope to support. Since gotham uses hyper, it should just be a matter of exposing whatever is needed to support this in hyper. We're certainly open to any PRs in this direction :)

**Comment by geromueller** [comment]
Maybe someone can create an example using this: https://docs.rs/websocket/0.23.0/websocket/server/upgrade/async/trait.IntoWs.html

**Comment by colinbankier** [comment]
We now have an example using websockets with Tungstenite https://github.com/gotham-rs/gotham/tree/master/examples/websocket
@dns2utf8 - does this give you what you wanted?
Gotham doesn't do any of the boilerplate for you (yet) - but this shows how you can do it.

**Comment by SchrodingerZhu** [comment]
@colinbankier 
the example failed to run in my test:
```
Listening on http://127.0.0.1:7878/
websocket init error: upgrade expected but low level API in use
websocket init error: upgrade expected but low level API in use
websocket init error: upgrade expected but low level API in use
```

**Comment by colinbankier** [comment]
Ok thanks @SchrodingerZhu . Do you have an example to reproduce your error?
cc @vickenty - you might be interested in this.

**Comment by SchrodingerZhu** [comment]
Just use the example:
```toml
gotham = {git = "https://github.com/gotham-rs/gotham"}
hyper = "0.12"
futures = "0.1"
tokio-tungstenite = "0.9"
pretty_env_logger = "0.3"
sha1 = "*"
base64 = "*"
futures-util = "*"
tokio = "*"
```
A simpler version like:
```rust
fn handler(mut state: State) -> (State, Response<Body>) {
    let body = Body::take_from(&mut state);
    let headers = HeaderMap::take_from(&mut state);

    if ws::requested(&headers) {
        let mut ws = WebSocketStream::from_raw_socket(body.on_upgrade(), Role::Server, None);
        let t = create_empty_response(&state, StatusCode::from_u16(101).unwrap());
        (state, t)
    } else {
        (state, Response::new(Body::from(INDEX_HTML)))
    }
}
```
can also trigger the error.

**Comment by vickenty** [comment]
The error means protocol upgrade is not enabled on the server connection. Looks like #356 accidentally removed `with_upgrades()` calls.
