### ISSUE TITLE
Move Askama/Gotham integration into Gotham

### ISSUE THREAD

**Issue by djc** [gotham-rs/gotham#355]
I have been struggling with the Askama integrations for different web frameworks. For now, Askama is not available from crates.io for actix-web 1.0 because there are conflicting dependencies between actix-web/Gotham/Rocket, all of which Askama supports. Due to coherency issues, I think the integration code will have to live inside either Gotham or Askama. I'd still be happy to do any maintenance work required on the integration, but at this point I think it would be better if the Gotham/Askama integration moves into the Gotham crate (since the latter has many more requirements on the dependency tree than Askama itself).

See #320 of the previous instance of this.

**Comment by msrd0** [comment]
It looks like the gotham-askama-integration is living inside a `askama_gotham` crate, which sounds like a good solution to me, so do you still want to move the integration code into gotham?

**Comment by djc** [comment]
Yeah, I think the solution I came up with is working fairly well, so this can be closed.
