### ISSUE TITLE
HandlerError::into_response doesn't log cause

### ISSUE THREAD

**Issue by fpgaminer** [gotham-rs/gotham#359]
It looks like the code for `HandlerError::into_response` is supposed to log the cause of the error:

https://github.com/gotham-rs/gotham/blob/154034fbe92b5a7ff1b1732b6ddcdf4fb82b31ec/gotham/src/handler/error.rs#L140

However, that doesn't seem to work; on 0.4.0 my logs just show None where the cause description should be.

As far as I can tell it's because that line is calling `self.source()`, but `HandlerError` only implements `cause`, not `source`:

https://github.com/gotham-rs/gotham/blob/154034fbe92b5a7ff1b1732b6ddcdf4fb82b31ec/gotham/src/handler/error.rs#L79-L87

And checking `Error`'s default implementation, `source` will indeed return `None` by default.

Though, I haven't tested a patch to be sure that my theory is correct.

**Comment by colinbankier** [comment]
Thanks for the report @fpgaminer .

**Comment by whitfin** [comment]
I've pushed up https://github.com/gotham-rs/gotham/pull/360 which might fix this, it seems like an improvement at the very least. @fpgaminer do you want to try that patch out and see if it works as you'd expect?

**Comment by msrd0** [comment]
I believe this has been fixed in #438, if not feel free to reopen.
