### ISSUE TITLE
Make TLS optional

### ISSUE THREAD

**Issue by msrd0** [gotham-rs/gotham#365]
Currently, gotham requires an outdated version of `tokio-rustls` by default, which can't be updated due to version conflicts of `ring` with `jsonwebtoken` (when using the middleware).

However, these version conflicts can also occur in the binary that's using gotham. Therefore I think it would be a good idea to make gotham's tls feature optional. This would be sufficient in my use case since my server is behind a reverse proxy anyways, and doesn't use the jwt middleware. I can't speak for other use cases though.

See also https://github.com/gotham-rs/gotham/pull/344 and [the `ring` version conflict](https://travis-ci.org/gotham-rs/gotham/jobs/570756164#L490).

**Comment by colinbankier** [comment]
Thanks @msrd0 . Making it optional seems like a good idea - particularly given your case of being behind a proxy would be common.
I'm sure we had a similar conflict with ring previously that was resolved - but I'm assuming this a new one as versions have moved forward.

@nyarly - thoughts on moving tls behind a feature?

**Comment by nyarly** [comment]
We've started talking about (and I'm starting to look at first steps towards) a more feature-controlled way of using Gotham. I'm happy to leave this issue open to ensure that the new approach addresses this concern.

**Comment by agraven** [comment]
I think this can be closed as the `rustls` feature has been introduced.

**Comment by msrd0** [comment]
With #422 merged I no longer see rustls as a dependency of gotham for my use case so I agree with @agraven that this can be closed. However, there might be other additional crates besides the diesel middleware that pull tls back in, so I'll leave it up to the maintainers to decide if this issue is completed yet.
