### ISSUE TITLE
What means blockchain keyword on crates.io?

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [gotham-rs/gotham#371]
You are the web-framework, am I right?

**Comment by colinbankier** [comment]
This was a joke some time ago that all things "cool" had to have "blockchain" as a keyword. Don't give it too much thought :) Perhaps it is time to undo that joke though. PRs accepted :)

**Comment by bradleybeddoes** [comment]
For the specific history of this: https://github.com/gotham-rs/gotham/commit/ff30c45fc3035d3a88a3f9a47d5ff4b160febf8c

**Comment by AngelicosPhosphoros** [comment]
@colinbankier OK, I have made: https://github.com/gotham-rs/gotham/pull/373
