### ISSUE TITLE
ContentTypeHeaderRouteMatcher matches too strict

### ISSUE THREAD

**Issue by msrd0** [gotham-rs/gotham#381]
I'm using gotham's `ContentTypeHeaderRouteMatcher` to only accept POST requests with `application/json` as their Content-Type. One application decided to send `application/json; charset=utf-8`. I'd expect this to be fine, however, gotham decides to answer with a _415 Unsupported Media Type_. I believe that gotham should behave less strict and accept the Content-Type even if additional information like a charset is given.

**Comment by msrd0** [comment]
I've implemented my own version of the content type and accept header matchers [here](https://gitlab.com/msrd0/gotham-restful/-/tree/master/gotham_restful/src/matcher), if you're interested I could create a PR and replace gotham's more basic matchers with those. They'd allow content types to specify additional information like the charset, and allow accept headers to contain the quality-weighted syntax as returned by browsers rather than just a single mime type (which is fine for most rest applications but triggers 415 responses when accessed through browsers).

**Comment by nyarly** [comment]
A quick review of that repo leaves me with a very good impression. I'd be inclined to merge such a PR. Thanks!
