### ISSUE TITLE
hyper should be re-exported by gotham

### ISSUE THREAD

**Issue by pksunkara** [gotham-rs/gotham#385]
Since it is pretty much bound to our handlers, we should just re-export `hyper` and update examples and docs to use `gotham::hyper`

**Comment by colinbankier** [comment]
Thanks @pksunkara - given the discussion over at https://github.com/rust-lang/api-guidelines/issues/176 I'd support a PR to re-export - this seems to be the recommended best-practice. Happy to hear any counter arguments ( @nyarly @whitfin ?) as there seems to be some differing opinions on it.

**Comment by pksunkara** [comment]
I will send a PR as soon as #370 is merged since I will be removing `hyper` dep from examples and that branch will conflict with mine.

**Comment by pksunkara** [comment]
Finished the change at https://github.com/reign-rs/gotham/commit/55029ff2e09baa4821799b202ea724cec1ef2948. Just waiting for #370 to be merged so that I can make a PR.

**Comment by colinbankier** [comment]
Great, thanks @pksunkara . Looking good :+1:

**Comment by pksunkara** [comment]
Made https://github.com/gotham-rs/gotham/pull/393
