### ISSUE TITLE
Help on determining path for static asset serving

### ISSUE THREAD

**Issue by yatesco** [gotham-rs/gotham#405]
[Not really a `gotham` specific question, but please help :-)]

Hi there,

I understand that the `FileOptions::new(path)` uses a relative path if it is something like `"assets"`, and this works fine if I run from the command line inside the cargo root via `cargo run`

However, if I start it from within IntelliJ's CLion then the working directory is somewhere else and `"assets"` is no longer correct.

What technique/strategy/magic do I need to do to figure out "always use the assets directory relative to the crate root"?

Thanks!

**Comment by colinbankier** [comment]
I think the best strategy would be to tell IntelliJ to set the right working dir when it runs the process. I don't use CLion so I'm not familiar with it, but suspect it must be a common option to be able to set?

**Comment by yatesco** [comment]
Thanks @colinbankier  - that's the right answer for now I think.
