### ISSUE TITLE
Including CSS and images in exe?

### ISSUE THREAD

**Issue by yatesco** [gotham-rs/gotham#406]
In Java land it is pretty convenient to bundle static assets in the WAR file. Is that possible/idiomatic in Rust or are assets put on the file system alongside the exe?

Thanks!

**Comment by colinbankier** [comment]
You could use something like https://github.com/pyros2097/rust-embed to embed them.
Personally, I'd usually use a docker container as the "packaging" - I guess it depends what suits your environment better.

**Comment by yatesco** [comment]
Thanks @colinbankier - unfortunately Windows 2008r2 - don't ask :-)
