### ISSUE TITLE
Fail (Return error) elegantly and handle subsequent requests correctly.

### ISSUE THREAD

**Issue by kahlil29** [gotham-rs/gotham#407]
I think this is more of a `Rust` related question rather than something to do with `Gotham` specifically : 

So I have an endpoint that accepts a folder path as a `path` param. 
Somewhere inside the code, there is a `fs::read_dir` call happening and if it finds the folder, everything is executed fine. 

The issue is that I am calling an `unwrap()` on the result of the `read_dir` which panics if the folder does not exist (is not found). This panic causes subsequent request to also fail and basically breaks my app. 

The errors (server-side) I get are : 
```
thread 'gotham-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'gotham-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5
thread 'gotham-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5
thread 'gotham-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5
```

If this is not a Gotham-specific issue then apologies from me in advance, I am fairly new to Rust. 
I would like to know what the best-practice is for these kind of things. 
Is it to use `?` and pass the errors up, inspect them at some point and return an error `String` ? 
That's my intuition but I may be wrong here.

**Comment by pksunkara** [comment]
https://doc.rust-lang.org/std/path/struct.Path.html#method.exists

**Comment by AngelicosPhosphoros** [comment]
Just do not call unwrap?
You can match the result and return 404 if not Ok.

**Comment by kahlil29** [comment]
Thanks @pksunkara @AngelicosPhosphoros 😄
