### ISSUE TITLE
Template for GUIs with seed+gotham - Potential use case/example

### ISSUE THREAD

**Issue by liketechnik** [gotham-rs/gotham#411]
Hey guys,
after posting my project on reddit, someone proposed to inform the seed contributors about it, but I though you could also be interested in this use case as a potential example.
The goal of my project is to provide an 'electron like' template, that allows to create local/desktop browser GUIs with access to the local filesystem (e. g. without the usual browser restrictions). I want this for a project where I want to render latex formula in my GUI and save a lot of files.
Using seed, [gotham](https://gotham.rs/), [rust-embed](https://github.com/pyros2097/rust-embed) and [web-view](https://github.com/Boscop/web-view) the template now compiles into a single, os independent binary, that directly opens in its own window.

Let me know your thoughts on the project and thanks for this wonderful library :)

P. S.: The project's repository is at: https://gitlab.com/liketechnik/local-gui-seed-gotham

**Comment by colinbankier** [comment]
Thanks for sharing @liketechnik! Very cool project. I'd be great to link to your project from some kind of "Who's using Gotham" page - I don't think we have one yet, but perhaps we should start one :)

**Comment by liketechnik** [comment]
Thanks for the kind feedback.

I could open a PR with that section in the readme if you'd like.

**Comment by nyarly** [comment]
Please do!

**Comment by msrd0** [comment]
#421 has been merged so I believe this can be closed.
