### ISSUE TITLE
How is security enforced?

### ISSUE THREAD

**Issue by tyoc213** [gotham-rs/gotham#419]
I mean, I have been using web2py that has the security in the description (just like gotham) in the project description and in the doc it is explained like this: http://www.web2py.com/book/default/chapter/01#Security so how is security enforced in gotham? or is only by rust (so all other rust frameworks could also put secure in their description?).

Thanks.

**Comment by nyarly** [comment]
Security is an ongoing and continual concern in the design and discussion process of Gotham. It's a lighter-touch framework than web2py, and as a result it can't protect developers to the same degree. That said, I'll candidly express some misgivings about using the OWASP Top Ten as a checklist for framework development.

**Comment by tyoc213** [comment]
Yes, please do, and it would be nice if security is in some place "documented" or expressed.
