### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by d0nutptr** [gotham-rs/gotham#428]
Hello! I just wanted to give you a heads up that https://gotham.rs appears to be down. It's currently not returning an `A` record when I query dns either.

![image](https://user-images.githubusercontent.com/4058559/81253697-fd64af80-8fdd-11ea-9e98-7f4f55285828.png)

**Comment by nyarly** [comment]
Thanks for the report. There was a flub with the registrar, which is in the process of being corrected. Should be back up in the next couple of hours.

**Comment by d0nutptr** [comment]
Looks to be back up! Thanks!!

**Comment by msrd0** [comment]
@inblossoms See https://github.com/gotham-rs/gotham.rs/issues/71
