### ISSUE TITLE
Pre-releases are not bad, please do one

### ISSUE THREAD

**Issue by pksunkara** [gotham-rs/gotham#429]
I have been trying to get the maintainers do a pre-release for the past few months but only met with failure. I understand that you guys don't want to do a 0.5.0 yet, but please for god's sake do a pre-release (`alpha`). Pre-releases by definition means you can still break stuff for the final 0.5.0 release. So, there should be no issue doing one now.

Actix has `3.0.0-alpha.2`
Clap has `3.0.0-beta.1`

If other popular crates are doing pre-releases, what's the blocker for this? There are many changes in the master branch which we want to use but we are blocked by the master branch not being released.

@nyarly, @whitfin Please do one. Or give @colinbankier access to do one. If you guys are busy to maintain the project, add other people. In fact, I am willing to maintain, so you can add me.

I understand how open source is voluntary only and you are not beholden to the users. But I don't want to see this project dead.

**Comment by rockstar** [comment]
The examples _are_ documentation, and they currently are out-of-date in a way that documentation isn't often out of date: it describes an unrealized future. A pre-release would at least help there.

**Comment by colinbankier** [comment]
I have managed to do a pre-release: https://crates.io/crates/gotham/0.5.0-rc.1
Thanks @nyarly @smangelsdorf for getting me access.
Let us know if you encounter any issues.
