### ISSUE TITLE
file handle should support customized encoding type in http response head

### ISSUE THREAD

**Issue by efancier-cn** [gotham-rs/gotham#444]
For single file web application, the common way to reduce the loading time is gzip the index.htm file and set the encoding field in response head, this also help embedded linux to reduce file system size - some of the cost sensitive embedded linux system use 32MB spi flash for bootloader, kernel and file system.

**Comment by sezna** [comment]
You could accomplish this with middleware or accessing/constructing the headers on the response directly -- it is just a [Hyper response](https://docs.rs/hyper/0.13.7/hyper/struct.Response.html). You could then gzip the response body bytes with something like [flate-2]](https://github.com/alexcrichton/flate2-rs).

**Comment by msrd0** [comment]
Just for clarification - is this something you expect a middleware to do, or are you suggesting that [`to_file`](https://docs.rs/gotham/0.5.0-rc.1/gotham/router/builder/trait.DefineSingleRoute.html#method.to_file) gets an option to do the gzip for you / only serve pre-gzip-ed files?
