### ISSUE TITLE
How to test handler functions in an isolated manner?

### ISSUE THREAD

**Issue by mknet** [gotham-rs/gotham#445]
As I understand the approach mentioned within the Hello World example on the Homepage a handler should be tested using the helpers of the `test` mod, like `TestServer`, `TestClient` and so on.
However, I come from a school saying that I should try to test my code as isolated as possible. So, I wonder if there'd a way of testing the handler function directly / without the need of starting a server, nor communicating via a network protocol. I did some "trials" and stuck at the point where I want to initialize the state struct.

The latest (non working) state of my latest trial can be found here: https://github.com/mknet/rust-contact-mailer/blob/trial/unit-test-handler/src/main.rs#L130

I'd be glad for any hint, correction or idea regarding my approach.
 
Thanks in advance

**Comment by msrd0** [comment]
I guess you can make your trial work by changing `handle_valid_body` to only take a (im)mutable reference to the `State` and have it not return that. You can then still construct the return value in your handler like `let res = handle_valid_body(&state, ...); (state, res)` but can also use it for testing, where obtaining an owned `State` is not possible. You then of course need to populate the state with the headers/cookies/body/..., everything you need for your handler that gotham usually takes care of.

That said, I (personally) wouldn't recommend this approach. Your handler so far looks pretty standalone, not making use of any middlewares, async or other features gotham has to offer. So as of right now, the only thing you obmit from testing with your isolated approach is the routing logic, which should not be that much of a big deal. As soon as you start relying on middlewares or convert your handlers to async ones (which you should do as soon as you use any I/O inside them), your isolated approach is going to become a nightmare. So I'd just go with gotham's `TestServer` and prevent yourself from getting a headache later on.

**Comment by mknet** [comment]
Thanks for your response and and help, @msrd0. I appreciate it.
I think I get your point.
But still there is a question. From my used approach I'd try to mock the method `send_fn` which I'm using in the handler. Is there any standard way of doing it using `TestServer`.

Thanks in advance

**Comment by msrd0** [comment]
I'm afraid I never tried to mock something like that, so I guess the best idea I can come up with is to make `send_fn` an argument of your `router` function and pass it on downwards, either through arguments or through a middleware. That is of course assuming you want to use the same `send_fn` for every handler.

Still, there might be a better solution that I'm not aware of.

**Comment by mknet** [comment]
Thanks for your answer, @msrd0 
It think, I found a solution by using mockall. I need to clean-up my code a bit and will link it here later on.
For now now, I'm gonna close the issue. Thanks again for you time, @msrd0.
