### ISSUE TITLE
CookieJar doesn't satisfy FromState, StateData

### ISSUE THREAD

**Issue by sezna** [gotham-rs/gotham#462]
Hi! I'm currently converting an old Iron project over to using Gotham, and I'm having a great time so far. Thanks for your work on Gotham, it's a great tool.

I'm having issues reading cookies using the cookie middleware. When I follow the examples for cookies, I end up with this error, which originates from outside of my crate.

```
 CookieJar::borrow_from(&state)
    |                    ^^^^^^^^^^^ function or associated item not found in `cookie::CookieJar`
    |
   ::: 
    |
84  | pub struct CookieJar {
    | --------------------
    | |
    | doesn't satisfy `cookie::CookieJar: gotham::state::FromState`
    | doesn't satisfy `cookie::CookieJar: gotham::state::StateData`
    |
    = note: the method `borrow_from` exists but the following trait bounds were not satisfied:
            `cookie::CookieJar: gotham::state::StateData`
            which is required by `cookie::CookieJar: gotham::state::FromState`
            `&cookie::CookieJar: gotham::state::StateData`
            which is required by `&cookie::CookieJar: gotham::state::FromState`
            `&mut cookie::CookieJar: gotham::state::StateData`
            which is required by `&mut cookie::CookieJar: gotham::state::FromState`
```

I do have `FromState` and `StateData` in scope, and my imports match the ones in the example. Additionally, I confirmed that no features are required for this example. Did the interface with `CookieJar` change? Or perhaps I am missing something?

Thanks,
Alex

**Comment by msrd0** [comment]
[`StateData`](https://docs.rs/gotham/0.5.0-rc.1/gotham/state/trait.StateData.html) is implemented for `CookieJar` (and so is `FromState`), can you confirm that you are using the same version of `cookie` as gotham does? That'd be `0.13.3` for the `0.5.0-rc.1` version of gotham.

**Comment by sezna** [comment]
Ah, that indeed fixed it. 

In the example, the [Cargo.toml file](https://github.com/gotham-rs/gotham/blob/master/examples/cookies/introduction/Cargo.toml#L13) has Cookie `0.14`. Is that a mistake, then?

**Comment by msrd0** [comment]
No, it's not a mistake, rather a happened-after-the-last-release thing. The code on https://crates.io counts (that is where cargo downloads the dependencies from), not the master branch on github :wink:

**Comment by sezna** [comment]
Oh okay, makes sense. Thank you for your help!
