### ISSUE TITLE
Update the tera example

### ISSUE THREAD

**Issue by msrd0** [gotham-rs/gotham#464]
The tera example uses the `compile_templates!` macro that has been removed in version 1.0 ([Changelog](https://github.com/Keats/tera/blob/master/CHANGELOG.md#100-2019-12-07)). It needs to be rewritten to compile with newer versions of tera.

Related: #460

**Comment by edjroz** [comment]
QQ, should the `lazy_static` be removed then ?

**Comment by msrd0** [comment]
I'm open to whether or not we continue using `lazy_static`, just the initialization code we currently use is no longer a thing in the latest version of `tera`.

**Comment by edjroz** [comment]
@msrd0 Quick observation for Hacktoberfest it seems the issues are tagged for Hacktoberfest but the repository is ineligible as the repository needs to add the topic `Hacktoberfest` to be eligible for the event.

**Comment by msrd0** [comment]
Srsly? A repository actively using the `hacktoberfest` tag is ineligible? Anyways, I've added the topic for now.
