### ISSUE TITLE
Lower tokio required features

### ISSUE THREAD

**Issue by ar3s3ru** [gotham-rs/gotham#499]
Hello :wave: 

I was looking through the dependencies of the project and I found this:
https://github.com/gotham-rs/gotham/blob/5ac2e3cfbcbdb7c69f655ecf0a10e3e4ee4de71d/gotham/Cargo.toml#L32

Does Gotham really need the `full` feature-set of Tokio in order to function? That brings _a lot_ of dependencies in...

**Comment by msrd0** [comment]
We probably don't need all features of tokio ... we should keep this in mind when upgrading to tokio 0.3 / hyper 0.14, I see little reason to change it right now.

**Comment by ar3s3ru** [comment]
I'm working on lowering the requirements, will try to post a PR shortly :+1:

**Comment by ar3s3ru** [comment]
As for tokio 0.3, hyper dependency is a blocker, so I would keep these two features separate.
