### ISSUE TITLE
Missing `Send` in `SessionData::discard`'s `Future`

### ISSUE THREAD

**Issue by jakubfijalkowski** [gotham-rs/gotham#580]
Hey there!

I stumbled on a following error. Consider the handler code:

```rust
pub async fn logout_handler(mut state: State) -> HandlerResult {
    let session = SessionData::<UserSession>::take_from(&mut state);
    session.discard(&mut state).await.unwrap();

    let response = create_empty_response(&state, StatusCode::OK);
    Ok((state, response))
}
```

attached to router using `to_async`. Nothing really fancy - just dropping the user state on logout. Before v0.6.1, the handler was synchronous, as `discard` returned plain `Result`. From 0.6.1 onward, `discard` returns a `Pin<Box<dyn Future<Output = Result<(), SessionError>>>>`. This is problematic, because the `Future` is not `Send`, so the future returned by `logout_handler` is also `!Send` and cannot be used in `to_async`.

Changing the signature of `discard` to
```rust
pub fn discard(
    self,
    state: &mut State,
) -> Pin<Box<dyn Future<Output = Result<(), SessionError>> + Send>> {
```

i.e. making the `Future` also `Send` works and solves the problem. I am not sure whether this is the correct approach - do I miss something here? I'm only starting with async Rust and I don't really feel like I know how it works, so sorry in advance if I missed something obvious. :)

**Comment by msrd0** [comment]
This looks like a problem in Gotham, likely introduced in #468

**Comment by jakubfijalkowski** [comment]
Yep, it also looks like a simple omission (since other `Futures` are aliased, and the alias has `Send`). Do you want a PR from me maybe (I can also write some tests for `discard`, as noted in the comment), or do you want to tackle it yourself?

**Comment by msrd0** [comment]
I just created a PR myself, but thanks for the offer
