### ISSUE TITLE
Consider the use of cookie prefixes

### ISSUE THREAD

**Issue by smangelsdorf** [gotham-rs/gotham#6]
Consider providing cookie prefixes by default, or supporting their use in a low-effort way:

https://www.chromestatus.com/feature/4952188392570880

**Comment by bradleybeddoes** [comment]
Incorrectly closed during source control system migration.

**Comment by colinbankier** [comment]
I'd like to try and take a look into this.

**Comment by colinbankier** [comment]
Looking at how other frameworks support this, I see Play does this:

> if you happen to be using these prefixes for cookie names Play will warn when serializing and deserializing those cookies if the proper attributes are not set, then set them for you automatically.

I assume we want to do something similar? i.e. it's up to the user to actually set a name, and this is more a helper to ensure the associated attributes are set.
Do we want to change the current default cookie name to include one of these prefixes?

I noticed that Play's implementation for `__Host-*` cookies ignores the "can't have `Domain`" part of the spec. I'm not sure if this is significant.

**Comment by bradleybeddoes** [comment]
> I assume we want to do something similar? i.e. it's up to the user to actually set a name, and this is more a helper to ensure the associated attributes are set.

I think that is where we'd want to start and see where the PR goes from there once we get a feel for the feature, certainly making life easy for developers who want to use a spec is the goal.

> Do we want to change the current default cookie name to include one of these prefixes?

I'm not sure on this, personally I'd be likely to wait until this feature PR lands and then consider changing other parts of Gotham to use it as a seperate concern (if we deem is useful/necessary).

> I noticed that Play's implementation for __Host-* cookies ignores the "can't have Domain" part of the spec. I'm not sure if this is significant.

Not sure, I'll need to look at the spec and get back to you. Generally speaking though I've found that any time you start to go away from a spec bad things happen, so it is probably best to be as true to the spec as possible.
