### ISSUE TITLE
Simple Middleware support

### ISSUE THREAD

**Issue by nyarly** [gotham-rs/gotham#74]
In my freshman app with Gotham I have:

```rust
mod app_config {
  use gotham::middleware::{NewMiddleware, Middleware};
  use gotham::state::State;
  use hyper::Request;
  use gotham::handler::HandlerFuture;
  use std::io;
  use std::env;
  use state::AppConfig;
  use futures::{future, Future};

  pub struct New {}

  impl NewMiddleware for New {
    type Instance = Ware;
    fn new_middleware(&self) -> io::Result<Self::Instance> {
      Ok(Ware {})
    }
  }

  pub struct Ware {}

  impl Middleware for Ware {
    fn call<Chain>(self, mut state: State, request: Request, chain: Chain) -> Box<HandlerFuture>
      where Chain: FnOnce(State, Request) -> Box<HandlerFuture> + Send + 'static,
            Self: Sized
    {
      let cfg = AppConfig {
        canonical_url: env::var("CANONICAL_URL").unwrap_or_default(),
        // ...
      };

      debug!("AppConfig: putting config in state");
      state.put(cfg);
      Box::new(future::ok(state).and_then(|state| chain(state, request)))
    }
  }
}
```

The only thing of interest there is the contents of the call method. It would be nice to only need to write/register that.

Could Middleware/NewMiddleware be implmented for a Fn trait?

This may be a simple as a macro, but I don't have the scope within Gotham to speak to the required generality.

**Comment by smangelsdorf** [comment]
Thanks for raising this. The `NewMiddleware` / `Middleware` split is not ideal in the very simple case, but is necessary to support anything more complex and especially something which involves a connection pool.

One way to handle this is by deriving `Clone` and then implementing `NewMiddleware` + `Middleware` like:

```rust
#[derive(Clone)]
struct MyType;

impl NewMiddleware for MyType {
  type Instance = Self;
  fn new_middleware(&self) -> io::Result<Self> {
    self.clone()
  }
}

impl Middleware for MyType {
  // ... implementation elided
}
```

We could make this easier by adding a custom derive for `NewMiddleware`, so the simple middleware definition could just be:

```rust
#[derive(Clone, NewMiddleware)]
struct MyType;

impl Middleware for MyType {
  // ... implementation elided
}
```

> Could Middleware/NewMiddleware be implmented for a Fn trait?

This might need a change to the `Middleware` trait to be achievable. The trouble is that `<M as Middleware>::call` needs to be generic in the type of the `Chain` function, which would look something like:

```rust
impl<F, C> Middleware for F // Err: Unconstrained type parameter `C`
where
  F: Fn(State, C) -> Box<HandlerFuture>
{
  fn call<Chain>(self, s: State, c: Chain) {
    self(s, c) // Err: C != Chain
  }
}
```

We could write this if we found a way to move the type of the `Chain` function to the `Middleware` trait, for example:

https://play.rust-lang.org/?gist=0a7c5ae40c14e2c0e0a5cce616c80e40&version=stable

One potential issue with this is pipeline construction may become impossible. Would need further exploration.
