### ISSUE TITLE
API design to get hold of a Tokio handle within a handler

### ISSUE THREAD

**Issue by ChristophWurst** [gotham-rs/gotham#78]
As discussed on Gitter with @bradleybeddoes, I'm missing the possibility to send new HTTP requests inside Gotham handlers because currently it's not possible to get a reference to the underlying Tokio event loop. 

@bradleybeddoes pointed me to https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/handler/mod.rs#L151 where other framework state variables are initialized. Unfortunately, I don't see a way of accessing the tokio handle in that function. As a matter of fact the whole Gotham codebase is pretty much unaware of the whole Tokio stuff because the way Gotham apps seem to be started is that the handler is passed to Hyper's server API. Hyper will either create the Tokio core internally, or let you use an existing one (since https://github.com/gotham-rs/gotham/pull/66).

An alternative to having Gotham put the handle reference into the state object would be to use a middleware for that: https://github.com/ChristophWurst/gotham-middleware-tokio. You can find an example usage here: https://github.com/ChristophWurst/gotham-middleware-tokio/blob/master/examples/hyper_client.rs#L22

There seem to be a few problems though. I don't know whether we should use a `Handle`, a `Remote` or let the developer choose. `Handle` cannot be shared across threads. However, Hyper expects a `Handle` rather than a `Remote` for its client, making it a bit cumbersome to use. The remote object does have method to get a handle, [although it's not guaranteed to always get one](https://docs.rs/tokio-core/0.1.11/tokio_core/reactor/struct.Remote.html#method.handle).

This is somewhat related to https://github.com/hyperium/hyper/issues/1002

@bradleybeddoes @smangelsdorf thoughts on how to integrate this in Gotham?

**Comment by bradleybeddoes** [comment]
I'm not sure what @smangelsdorf had in mind but I was thinking of something along the lines of passing a handle reference to https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/handler/mod.rs#L123 and then  being able to use that within https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/handler/mod.rs#L151 to push it into `state`.

I may be missing some importance nuance here as I've only very briefly considered this, happy to keep kicking this around if I've overlooked something important.

If we do change https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/handler/mod.rs#L123 then https://github.com/gotham-rs/gotham/pull/70 will need to consider the impact.

**Comment by rcaught** [comment]
Related: #69 will need access to the event loop as well.

**Comment by smangelsdorf** [comment]
> I don't know whether we should use a `Handle`, a `Remote` or let the developer choose. `Handle` cannot be shared across threads. However, Hyper expects a `Handle` rather than a `Remote` for its client, making it a bit cumbersome to use.

Tokio [was discussing a change](https://tokio.rs/blog/tokio-reform/) which merges both these types into a `Handle` which is also usable in the way `Remote` is currently used. If that's still their plan ([which seems likely](https://github.com/tokio-rs/tokio-rfcs/pull/3)), sticking with what Hyper wants will ensure we automatically get the benefit of this refactor when it happens.

**Comment by smangelsdorf** [comment]
@bradleybeddoes:

> […] passing a handle reference to https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/handler/mod.rs#L123 and then  being able to use that within https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/handler/mod.rs#L151 to push it into `state`

One complicating factor here is that we're creating a `NewHandlerService` and then cloning it for each connection: https://github.com/gotham-rs/gotham/blob/953c39b6d5d5134bbab5ab658f1aadc243a68806/src/clone_sockets.rs#L21-L35

The structure here might have to change a bit, to have `NewHandlerService::new` take an `Arc<T>` and a `Handle`. The local `serve` function could then be changed to take the `Arc<T>` and have it create the `NewHandlerService`.

With this small refactor I think your suggestion will work well. 👍

**Comment by smangelsdorf** [comment]
>  then #70 will need to consider the impact.

I can't see where there would be any impact on #70. Did you have something specific in mind?

**Comment by bradleybeddoes** [comment]
> I can't see where there would be any impact on #70. Did you have something specific in mind?

Apologies I mis-spoke on this one, please ignore that comment.

**Comment by bradleybeddoes** [comment]
🎉 :joy: :dizzy: :love_letter: :mega:
