### ISSUE TITLE
Consider allowing session cookie to have explicit lifetime supplied

### ISSUE THREAD

**Issue by smangelsdorf** [gotham-rs/gotham#8]
Currently our session cookies are _proper_ session cookies, which (except where defeated by certain modern browser features) are removed at the end of a browser session. Might it be useful to allow the lifetime to be set explicitly?

There are two problems with this from a security point of view:

* If the cookie expires on the client side but not the server side, the cookie value is not invalidated. If somebody has stolen the cookie, they can keep using it to keep refreshing the TTL (i.e. false sense of security for apps that set an expiry and expect it to behave correctly); and
* The cookie survives browser restarts, which is the common way that end users are instructed to ensure logout is completely effective.

**Comment by bradleybeddoes** [comment]
I've considered this a lot and I've come down on the side of not wanting to add this in.

I'm happy to close this issue if you're of the same opinion @smangelsdorf.

**Comment by smangelsdorf** [comment]
Agreed.
