### ISSUE TITLE
deriving PathExtractor and StaticResponseExtender depends on `use`ing modules the right way in client code

### ISSUE THREAD

**Issue by radix** [gotham-rs/gotham#80]
Generally macros shouldn't have dependencies on the environment in which they're run, but I noticed that deriving `PathExtractor` and `StaticResponseExtender` assumes that I have `hyper` and `gotham` imported bare in my modules. I think the usual way to avoid this is to use fully-qualified module names by prefixing with `::`

**Comment by smangelsdorf** [comment]
Thanks for reporting this. This has been bothering me too, I've added to the 0.2 milestone so we don't forget to address it.
