### ISSUE TITLE
Broken example due to missing imports

### ISSUE THREAD

**Issue by nihiluis** [gotham-rs/gotham#91]
I tried the Hello Router example but seem unable to find some imports.

I seem to have a different version as the example (0.1.2). This might be a bug.

```
error[E0432]: unresolved import `gotham::router::builder`
  --> src/main.rs:30:21
   |
30 | use gotham::router::builder::{build_simple_router, DefineSingleRoute, DrawRoutes};
   |                     ^^^^^^^ Could not find `builder` in `router`

error[E0425]: cannot find function `start` in module `gotham`
  --> src/main.rs:46:13
   |
46 |     gotham::start(addr, router())
   |             ^^^^^ not found in `gotham`
```

deps:
```
gotham = "0.1"
gotham_derive = "0.1"
mime = "0.3"
```

this is my local lib.rs of Gotham
```
//! Gotham - A flexible web framework that does not sacrifice safety, security or speed.
//!
//! You can find out more about Gotham, including where to get help,  at https://gotham.rs.
//!
//! We look forward to welcoming you into the Gotham community!
#![doc(html_root_url = "https://docs.rs/gotham/0.1.2")] // Update when changed in Cargo.toml
#![warn(missing_docs, deprecated)]
#![doc(test(no_crate_inject, attr(deny(warnings))))]
// TODO: Remove this when it's a hard error by default (error E0446).
// See Rust issue #34537 <https://github.com/rust-lang/rust/issues/34537>
#![deny(private_in_public)]

#[macro_use]
extern crate hyper;
extern crate futures;
extern crate futures_cpupool;
extern crate tokio_core;
extern crate tokio_io;
extern crate mio;
extern crate borrow_bag;
extern crate url;
extern crate uuid;
#[macro_use]
extern crate log;
extern crate chrono;
extern crate mime;
extern crate serde;
extern crate rand;
extern crate base64;
extern crate rmp_serde;
extern crate linked_hash_map;

#[cfg(test)]
#[macro_use]
extern crate serde_derive;

pub mod handler;
pub mod middleware;
pub mod http;
pub mod router;
pub mod state;
pub mod test;
```

**Comment by smangelsdorf** [comment]
Thanks for reporting this @nihiluis. To help me look into this for you, could you let me know which example you're trying to run please?

**Comment by nihiluis** [comment]
the Hello Router one. the issue is that my just downloaded Gotham copy (from cargo) differs from the one the example relates to. There's no module builder and no function start in the lib (unlike on github).

**Comment by smangelsdorf** [comment]
That's correct, and that's the reason our example app refers to Gotham dependency by path rather than the released version:

https://github.com/gotham-rs/gotham/blob/cae665d739273e0f3d4b4adfbbe5072db8766a72/examples/hello_router/Cargo.toml#L12

Our examples are being rewritten to work for the impending `0.2` release, which includes a lot of new features (and the router builder, as you noticed). If you revert to the example app which references Gotham by relative path, that should resolve the compile errors.
